TARGET_VELOCITY: 0.8
VELOCITY_RESOLUTION: 0.05
OMEGA_RESOLUTION: 0.02 
PREDICT_TIME: 30.0
TO_GOAL_COST_GAIN: 3.0
SPEED_COST_GAIN: 5.0
OBSTACLE_COST_GAIN: 10.0
CURVATURE_COST_GAIN: 3.0
HEAD_COST_GAIN: 0.0
ANGLE_RESOLUTION: 0.0087
MAX_DIST: 10.0 
GOAL_THRESHOLD: 1.0
TURN_DIRECTION_THRESHOLD: 0.1

