ROBOT_FRAME: "base_link"
MAX_VELOCITY: 0.4
MIN_VELOCITY: 0.2
MAX_GAMMA: 0.52
MIN_GAMMA: -0.52
MAX_ACCELERATION: 1.0
MAX_OMEGA: 1.0
WHELL_AXLE_LENGTH: 1.2
CAR_WIDTH: 1.0
CAR_FRONT_2_AKMAN_LENGTH: 1.8
CAR_BACK_2_AKMAN_LENGTH: 0.55
EXPANSION_DISTANCE_WIDTH: 0.2
EXPANSION_DISTANCE_LENGTH: 0.1
LIDAR_2_AKMAN_OFFSET_X: 0.5