ROBOT_FRAME: "base_link"
MAX_VELOCITY: 0.4
MIN_VELOCITY: 0.1
MAX_GAMMA: 0.52
MIN_GAMMA: -0.52
MAX_ACCELERATION: 1.0
MAX_OMEGA: 1.0
WHELL_AXLE_LENGTH: 0.863
CAR_WIDTH: 1.028
CAR_FRONT_2_AKMAN_LENGTH: 1.315
CAR_BACK_2_AKMAN_LENGTH: 0.455
EXPANSION_DISTANCE_WIDTH: 0.2
EXPANSION_BACK_DISTANCE_LENGTH: 0.1
EXPANSION_FRONT_DISTANCE_LENGTH: 0.2
LIDAR_2_AKMAN_OFFSET_X: 0.37